---
abstract: 'An Apache2 Handler JavaScript Preprocessor designed for large scale javascript development'
author:
  - 'Daichi Hiroki <hirokidaichi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-Ectype-Handler-Apache2
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Date: 0
  JavaScript::Ectype: 0
  mod_perl2: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.1
